const app=document.querySelector('#app'),toastEl=document.querySelector('#toast'),L=['A','B','C','D'];
let user,screen='auth',bank=[],selected=[],uploads={},attempt,timer;
const api=async(p,o={})=>{let r=await fetch(p,{...o,headers:{...(o.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(o.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d};
const toast=t=>{toastEl.textContent=t;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])).replace(/\[\[visual:([^\]]+)\]\]/g,(_,path)=>`<img src="/api/media/${encodeURIComponent(path)}" alt="Original rendered question with equations, options, and diagrams" style="display:block;max-width:100%;max-height:680px;object-fit:contain;margin:14px 0;border:1px solid #dbe3ef;border-radius:8px;background:#fff">`);
function shell(c){app.innerHTML=`<div class="shell"><header class="topbar"><button class="brand" onclick="home()">Test<i>Now</i><small>CBT ENGINE</small></button><div class="profile"><span>${esc(user.name)} · ${user.role}</span><div class="avatar">${user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><button class="secondary" onclick="logout()">Sign out</button></div></header>${c}</div>`}
function auth(){clearInterval(timer);app.innerHTML=`<main class="auth-page"><section class="auth-panel"><div class="brand">Test<i>Now</i><small>CBT ENGINE</small></div><span class="eyebrow">ASSESSMENT DELIVERY</span><h1>Run tests. Review learning.</h1><p>Teacher and student accounts, secure server-side scoring, persistent attempts, and source-paper uploads.</p><div class="demo-box"><b>Seeded accounts</b><br>Teacher: <code>teacher@testnow.local</code> / <code>teacher123</code><br>Student: <code>student@testnow.local</code> / <code>student123</code></div></section><section class="auth-form card"><div class="mode-switch"><button id="loginTab" class="active" onclick="tab('login')">Sign in</button><button id="registerTab" onclick="tab('register')">Create account</button></div><div id="authBody"></div></section></main>`;tab('login')}
function tab(k){document.querySelectorAll('.mode-switch button').forEach(b=>b.classList.toggle('active',b.id===k+'Tab'));document.querySelector('#authBody').innerHTML=k==='login'?`<h2>Welcome back</h2><p>Sign into your workspace.</p><form onsubmit="login(event)"><div class="field"><label>Email</label><input name="email" type="email" value="teacher@testnow.local" required></div><div class="field"><label>Password</label><input name="password" type="password" value="teacher123" required></div><button class="primary wide">Sign in →</button></form>`:`<h2>Create account</h2><p>Create a teacher or student login.</p><form onsubmit="register(event)"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Role</label><select name="role"><option value="teacher">Teacher</option><option value="student">Student</option></select></div><div class="field"><label>Password</label><input name="password" type="password" minlength="8" required></div><button class="primary wide">Create account →</button></form>`}
async function login(e){e.preventDefault();try{user=(await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).user;home()}catch(x){toast(x.message)}}
async function register(e){e.preventDefault();try{user=(await api('/api/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).user;home()}catch(x){toast(x.message)}}
async function logout(){await api('/api/auth/logout',{method:'POST'});user=null;auth()} function home(){screen=user.role==='teacher'?'teacher':'student';render()}
async function render(){clearInterval(timer);if(!user)return auth();try{if(screen==='teacher')return teacher();if(screen==='builder')return builder();if(screen==='student')return student();if(screen==='exam')return exam();if(screen==='result')return result()}catch(x){toast(x.message)}}
async function teacher(){let d=await api('/api/teacher/tests');shell(`<main class="page"><div class="hero"><div><span class="eyebrow">Teacher workspace</span><h1>Control every test moment.</h1><p>Create, publish, and enroll students from a persistent workspace.</p></div><button class="primary" onclick="screen='builder';render()">+ Create test</button></div><section class="grid stats"><div class="card stat"><span>LIVE TESTS</span><strong>${d.tests.filter(t=>t.status==='live').length}</strong></div><div class="card stat"><span>QUESTION BANK</span><strong>25</strong></div><div class="card stat"><span>STORAGE</span><strong>SQLite</strong></div><div class="card stat"><span>ACCESS</span><strong>Roles</strong></div></section><section class="card"><div class="section-title"><h2>Your assessments</h2></div>${d.tests.map(t=>`<div class="test-row"><div><div class="test-title">${esc(t.title)}</div><div class="test-meta">${esc(t.subject)} · ${t.duration_minutes} min · ${t.question_count} questions · ${t.marks} marks</div></div><div style="display:flex;gap:9px;align-items:center"><span class="pill">${t.status}</span><button class="secondary" onclick="enroll(${t.id})">Enroll student</button></div></div>`).join('')||'<p>No tests created yet.</p>'}</section></main>`)}
async function builder(){bank=(await api('/api/question-bank')).questions;let chapters=[...new Set(bank.map(q=>q.chapter))];shell(`<main class="page"><div class="hero"><div><span class="eyebrow">Assessment builder</span><h1>Build a live assessment.</h1><p>Attach a source paper, choose bank questions, and publish.</p></div><button class="secondary" onclick="screen='teacher';render()">← Dashboard</button></div><section class="card form-card"><div class="form-grid"><div class="field"><label>Test title</label><input id="title" value="Physics Unit Test"></div><div class="field"><label>Subject</label><input id="subject" value="Physics"></div><div class="field"><label>Duration minutes</label><input id="duration" type="number" value="60"></div><div class="field"><label>Total marks</label><input id="marks" type="number" value="75"></div></div><div class="form-grid" style="margin-top:18px"><div class="upload-zone"><strong>Question paper PDF</strong><span id="paperStatus">Choose a PDF to extract text.</span><label for="paper"> browse files<input id="paper" type="file" accept="application/pdf" onchange="upload()"></label></div><div class="upload-zone"><strong>Answer key PDF</strong><span id="keyStatus">Optional source key.</span><label for="answerKey"> browse files<input id="answerKey" type="file" accept="application/pdf" onchange="upload()"></label></div></div><div id="extract"></div></section><section class="grid bank-layout" style="margin-top:18px"><aside class="card filters"><h2 style="margin-top:0;font-size:15px">Question filters</h2><label>Chapter</label><select id="chapter" onchange="showBank()"><option value="all">All chapters</option>${chapters.map(x=>`<option>${esc(x)}</option>`).join('')}</select><label>Type</label><select id="kind" onchange="showBank()"><option value="all">All types</option><option>MCQ</option><option>Numerical</option></select><label>Difficulty</label><select id="diff" onchange="showBank()"><option value="all">All levels</option><option>Easy</option><option>Medium</option><option>Hard</option></select><div class="notice">Uploads are stored on the server and their extractable text is displayed. Select bank questions to finalize the paper.</div></aside><section id="bank" class="card"></section></section></main>`);showBank()}
function showBank(){let ch=document.querySelector('#chapter')?.value||'all',k=document.querySelector('#kind')?.value||'all',d=document.querySelector('#diff')?.value||'all',q=bank.filter(x=>(ch==='all'||x.chapter===ch)&&(k==='all'||x.kind===k)&&(d==='all'||x.difficulty===d));document.querySelector('#bank').innerHTML=`<div class="section-title"><h2>${q.length} questions</h2><span>${selected.length} selected</span></div>${q.map(x=>`<article class="qbank-item"><header><span>${esc(x.source)} · ${esc(x.chapter)}</span><span>${esc(x.kind)} · ${esc(x.difficulty)}</span></header><p>${esc(x.prompt)}</p><button class="${selected.includes(x.id)?'primary':'secondary'}" onclick="selectQ(${x.id})">${selected.includes(x.id)?'Selected ✓':'Add to paper'}</button></article>`).join('')}<div class="selection"><span><b>${selected.length}</b> selected</span><button onclick="publish()">Publish test →</button></div>`}
function selectQ(id){selected=selected.includes(id)?selected.filter(x=>x!==id):[...selected,id];showBank()}
async function upload(){let f=new FormData(),p=document.querySelector('#paper').files[0],k=document.querySelector('#answerKey').files[0];if(p)f.append('paper',p);if(k)f.append('answer_key',k);if(!p&&!k)return;try{let d=await api('/api/upload',{method:'POST',body:f});uploads=d.uploads;if(uploads.paper)document.querySelector('#paperStatus').textContent='Saved: '+uploads.paper.filename;if(uploads.answer_key)document.querySelector('#keyStatus').textContent='Saved: '+uploads.answer_key.filename;let text=uploads.paper?.text_preview||uploads.answer_key?.text_preview||'';document.querySelector('#extract').innerHTML=`<div class="notice"><b>Extraction complete.</b> ${esc(text.slice(0,360)||'No machine-readable text found; file was still stored.')}</div>`;toast('Source file uploaded')}catch(x){toast(x.message)}}
async function publish(){if(!selected.length)return toast('Select at least one question.');try{await api('/api/tests',{method:'POST',body:JSON.stringify({title:document.querySelector('#title').value,subject:document.querySelector('#subject').value,duration_minutes:+document.querySelector('#duration').value,marks:+document.querySelector('#marks').value,question_ids:selected,status:'live',paper_filename:uploads.paper?.stored,key_filename:uploads.answer_key?.stored})});selected=[];uploads={};screen='teacher';toast('Test published');render()}catch(x){toast(x.message)}}
async function enroll(id){let email=prompt('Registered student email:');if(!email)return;try{await api(`/api/tests/${id}/enroll`,{method:'POST',body:JSON.stringify({email})});toast('Student enrolled')}catch(x){toast(x.message)}}
async function student(){let d=await api('/api/student/tests');shell(`<main class="page"><div class="hero"><div><span class="eyebrow">Student portal</span><h1>Your available tests</h1><p>Attempts and results are saved to your account.</p></div></div><section class="grid student-layout">${d.tests.map(t=>`<article class="card ${t.submitted_at?'':'start-card'}"><span class="pill">${t.submitted_at?'Completed':'Available now'}</span><h2 style="margin:15px 0 4px">${esc(t.title)}</h2><p>${esc(t.subject)} · ${t.question_count} questions · ${t.duration_minutes} minutes</p><button class="${t.submitted_at?'secondary':'primary'}" onclick="${t.submitted_at?`openResult(${t.attempt_id})`:`start(${t.id})`}">${t.submitted_at?'View result':'Start test →'}</button></article>`).join('')||'<div class="card">No live tests have been assigned to you.</div>'}</section></main>`)}
async function start(id){try{let d=await api(`/api/tests/${id}/attempts`,{method:'POST',body:'{}'});loadAttempt(d.attempt_id)}catch(x){toast(x.message)}}
async function loadAttempt(id){let d=await api(`/api/attempts/${id}`);attempt={id,...d,index:0,end:Date.now()+d.attempt.remaining_seconds*1000};screen='exam';render()}
const time=n=>`${String(Math.floor(Math.max(n,0)/60)).padStart(2,'0')}:${String(Math.max(n,0)%60).padStart(2,'0')}`;
function exam(){let q=attempt.questions[attempt.index],a=attempt.answers[q.id]||{},left=Math.floor((attempt.end-Date.now())/1000);app.innerHTML=`<div class="exam-shell"><header class="exam-head"><div class="brand">Test<i>Now</i><small>EXAM CONSOLE</small></div><span>${esc(attempt.attempt.subject)} · CBT session</span><div id="timer" class="timer">${time(left)}</div></header><div class="exam-grid"><main class="question-area"><div class="q-top"><span>QUESTION ${attempt.index+1} OF ${attempt.questions.length}</span><span>${q.kind.toUpperCase()} · +4 / −1</span></div><div class="question"><h2>${esc(q.prompt)}</h2>${q.kind==='MCQ'?`<div class="options">${q.options.map((x,i)=>`<button class="option ${String(a.response)===String(i)?'selected':''}" onclick="answer(${i})"><span class="letter">${L[i]}</span>${esc(x)}</button>`).join('')}</div>`:`<input class="numeric" type="number" value="${esc(a.response??'')}" onchange="answer(this.value)" placeholder="Enter numerical answer">`}</div><footer class="q-actions"><button class="clear" onclick="answer(null)">Clear response</button><div class="right"><button class="mark" onclick="review()">${a.reviewed?'Remove review':'Mark for review'}</button><button class="save" onclick="move(1)">Save & Next →</button></div></footer></main><aside class="palette"><div class="candidate"><div class="avatar">${user.name[0]}</div><div><b>${esc(user.name)}</b><br><span style="font-size:11px;color:var(--muted)">Server-saved session</span></div></div><b style="font-size:12px">Question palette</b><div class="numbers">${attempt.questions.map((x,i)=>{let z=attempt.answers[x.id]||{};return `<button class="num ${i===attempt.index?'active':''} ${z.response!==undefined&&z.response!==null&&z.response!==''?'answered':''} ${z.reviewed?'review':''}" onclick="jump(${i})">${i+1}</button>`}).join('')}</div><button class="submit" onclick="confirmSubmit()">Submit test</button></aside></div></div>`;timer=setInterval(()=>{let n=Math.floor((attempt.end-Date.now())/1000),e=document.querySelector('#timer');if(e)e.textContent=time(n);if(n<=0){clearInterval(timer);submit()}},1000)}
async function persist(){let q=attempt.questions[attempt.index],a=attempt.answers[q.id]||{};await api(`/api/attempts/${attempt.id}/answer`,{method:'POST',body:JSON.stringify({question_id:q.id,response:a.response,reviewed:!!a.reviewed,remaining_seconds:Math.max(0,Math.floor((attempt.end-Date.now())/1000))})})}
async function answer(v){let id=attempt.questions[attempt.index].id;attempt.answers[id]={...(attempt.answers[id]||{}),response:v};try{await persist();render()}catch(x){toast(x.message)}}
async function review(){let id=attempt.questions[attempt.index].id;attempt.answers[id]={...(attempt.answers[id]||{}),reviewed:!attempt.answers[id]?.reviewed};await persist();render()}
async function move(n){await persist();attempt.index=Math.min(attempt.questions.length-1,attempt.index+n);render()} async function jump(i){await persist();attempt.index=i;render()}
function confirmSubmit(){let n=Object.values(attempt.answers).filter(x=>x.response!==null&&x.response!==undefined&&x.response!=='').length;document.body.insertAdjacentHTML('beforeend',`<div class="modal-back" id="modal"><div class="modal"><span class="eyebrow">Final check</span><h2>Submit your test?</h2><p>${n} of ${attempt.questions.length} questions answered. Results and solutions unlock immediately.</p><div class="actions"><button class="secondary" onclick="document.querySelector('#modal').remove()">Keep reviewing</button><button class="primary" onclick="submit()">Submit now</button></div></div></div>`)}
async function submit(){clearInterval(timer);document.querySelector('#modal')?.remove();try{await api(`/api/attempts/${attempt.id}/submit`,{method:'POST',body:'{}'});screen='result';render()}catch(x){toast(x.message)}} async function openResult(id){attempt={id};screen='result';render()}
async function result(){let d=await api(`/api/attempts/${attempt.id}/review`),a=d.answers,total=a.length,answered=a.filter(x=>x.response!==null&&x.response!=='').length,correct=a.filter(x=>x.correct).length,wrong=answered-correct; shell(`<main class="page"><section class="results-hero"><div><span class="eyebrow" style="color:#aecaFF">Test complete</span><h1>${esc(d.attempt.title)}</h1><p style="color:#c7d6ed">${answered} attempted · server-evaluated</p></div><div class="score">${correct*4-wrong}<small> / ${total*4}</small></div></section><section class="grid result-grid"><div class="card stat"><span>ACCURACY</span><strong>${answered?Math.round(correct/answered*100):0}%</strong></div><div class="card stat"><span>CORRECT</span><strong style="color:var(--green)">${correct}</strong></div><div class="card stat"><span>INCORRECT</span><strong style="color:var(--red)">${wrong}</strong></div><div class="card stat"><span>UNATTEMPTED</span><strong>${total-answered}</strong></div></section><section class="card"><div class="section-title"><h2>Answer key & solutions</h2><button class="secondary" onclick="screen='student';render()">Back to tests</button></div>${a.map((x,i)=>`<article class="answer-row"><b>Q${i+1}. ${esc(x.prompt)}</b><p>Your response: <span class="${x.response===null?'':x.correct?'correct':'wrong'}">${x.response===null?'Not attempted':x.kind==='MCQ'?L[+x.response]||x.response:x.response}</span> · Correct: <span class="correct">${x.kind==='MCQ'?L[+x.answer]:x.answer}</span></p><p><b>Solution:</b> ${esc(x.solution)}</p></article>`).join('')}</section></main>`)}
async function boot(){try{user=(await api('/api/me')).user;user?home():auth()}catch{auth()}}boot();

// Upgrade every browser-uploaded PDF into the same visual, equation-preserving draft flow.
const browserUpload = upload;
window.upload = async function(){
  await browserUpload();
  if (!uploads.paper) return;
  const host=document.querySelector('#extract');
  if (!host) return;
  host.insertAdjacentHTML('beforeend', '<button class="primary" style="margin-top:10px" onclick="importUploadedPaper()">Import visual questions as draft →</button>');
};
async function importUploadedPaper(){
  try{
    const result=await api('/api/import-paper',{method:'POST',body:JSON.stringify({stored:uploads.paper.stored})});
    toast(`${result.question_count} visual questions imported as a draft`);
    screen='teacher'; render();
  }catch(error){toast(error.message)}
}
