"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import katex from "katex";
type User={id:string;name:string;email:string;role:"teacher"|"student"|"admin"};
type Question={id:string;source_number?:string;kind:string;stem_markdown:string;options:any[];answer?:any;solution_markdown?:string;confidence?:number;approved?:boolean;scoring?:any;diagrams?:any[]};
type ImportJob={id:string;status:"uploaded"|"processing"|"review"|"failed"|"approved";filename?:string;error?:string;meta?:{phase?:string;question_count?:number};created_at?:string;questions?:Question[]};
const api=async(path:string,options:RequestInit={})=>{const r=await fetch(`/api${path}`,{...options,credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:"Request failed"}))).detail||"Request failed");return r.status===204?null:r.json()};
function MathText({value}:{value:string}){const chunks=value.split(/(\$\$[\s\S]*?\$\$|\$[^$]+\$)/g);return <>{chunks.map((c,i)=>c.startsWith("$")?<span className="math" key={i} dangerouslySetInnerHTML={{__html:katex.renderToString(c.replace(/^\$\$?|\$\$?$/g,""),{throwOnError:false,displayMode:c.startsWith("$$")})}}/>:<span key={i}>{c}</span>)}</>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function Portal(){
 const [user,setUser]=useState<User|null>(null),[error,setError]=useState(""),[view,setView]=useState<"home"|"import"|"reviews"|"builder"|"exam"|"result">("home"),[tests,setTests]=useState<any[]>([]),[questions,setQuestions]=useState<Question[]>([]),[jobs,setJobs]=useState<ImportJob[]>([]),[selectedJobId,setSelectedJobId]=useState<string|null>(null),[attempt,setAttempt]=useState<any>(null),[index,setIndex]=useState(0),[message,setMessage]=useState("");
 const previousJobs=useRef<Map<string,string>>(new Map());
 const loadImports=async()=>{const next:ImportJob[]=await api("/teacher/imports");const previous=previousJobs.current;const completed=next.find(job=>previous.get(job.id)==="processing"&&job.status==="review");if(completed)setMessage("Import complete — questions are ready for review.");previousJobs.current=new Map(next.map(job=>[job.id,job.status]));setJobs(next);return next};
 const load=async(u?:User)=>{const me=u||await api("/auth/me");setUser(me);if(me.role==="teacher"||me.role==="admin"){const [loadedTests,loadedQuestions]=await Promise.all([api("/tests"),api("/questions")]);setTests(loadedTests);setQuestions(loadedQuestions);await loadImports()}else setTests(await api("/student/tests"))};
 useEffect(()=>{load().catch(()=>{})},[]);
 useEffect(()=>{if(!jobs.some(job=>job.status==="uploaded"||job.status==="processing"))return;const timer=window.setInterval(()=>loadImports().catch(()=>{}),3000);return()=>window.clearInterval(timer)},[jobs]);
 useEffect(()=>{if(!message)return;const timer=window.setTimeout(()=>setMessage(""),5000);return()=>window.clearTimeout(timer)},[message]);
 const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");try{const x=await api("/auth/login",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});await load(x)}catch(e:any){setError(e.message)}};
 if(!user)return <main className="auth"><div className="brand"><b>TestNow</b><span>SECURE CBT DELIVERY</span><h1>Assessment, delivered with confidence.</h1><p>Structured questions, governed publication, and server-authoritative exam delivery.</p></div><Card><h2>Sign in</h2><form onSubmit={login}><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/><button>Continue</button></form>{error&&<p className="error">{error}</p>}<small>Production accounts are created through invitations. Local API registration remains available for development.</small></Card></main>;
 const logout=async()=>{await api("/auth/logout",{method:"POST"});setUser(null);setView("home")};
 const selectedJob=jobs.find(job=>job.id===selectedJobId)||null;
 return <main><header><div className="logo">Test<span>Now</span></div><nav>{user.role!=="student"&&<><button onClick={()=>setView("home")}>Dashboard</button><button onClick={()=>setView("import")}>Import paper</button><button onClick={()=>setView("reviews")}>Review papers</button><button onClick={()=>setView("builder")}>Build test</button></>}<button onClick={logout}>Sign out</button></nav></header>{message&&<div className="toast">{message}</div>}
 {view==="home"&&(user.role==="student"?<StudentHome tests={tests} start={async id=>{setAttempt(await api(`/tests/${id}/attempts`,{method:"POST"}));setIndex(0);setView("exam")}}/>:<TeacherHome tests={tests} questions={questions} jobs={jobs} openImport={id=>{setSelectedJobId(id);setView("import")}} />)}
 {view==="import"&&<ImportScreen onDone={async job=>{setSelectedJobId(job.id);setJobs(current=>[job,...current]);previousJobs.current.set(job.id,job.status);setView("reviews");setMessage("Import queued. Track it in the dedicated paper review workspace.");}} job={null} jobs={[]} selectJob={setSelectedJobId} refresh={async()=>{}}/>}
 {view==="reviews"&&<ImportScreen reviewOnly onDone={()=>{}} job={selectedJob} jobs={jobs} selectJob={setSelectedJobId} refresh={async()=>{if(!selectedJobId)return;const updated=await api(`/teacher/imports/${selectedJobId}`);setJobs(current=>current.map(job=>job.id===updated.id?updated:job));previousJobs.current.set(updated.id,updated.status)}}/>}
 {view==="builder"&&<Builder questions={questions} onDone={async()=>{await load(user);setView("home");setMessage("Draft created. Publish it when review is complete.")}}/>}
 {view==="exam"&&attempt&&<Exam attempt={attempt} index={index} setIndex={setIndex} finish={async()=>{await api(`/attempts/${attempt.id}/submit`,{method:"POST"});setView("result")}} update={async(qid,answer,marked)=>{const x=await api(`/attempts/${attempt.id}/responses/${qid}`,{method:"PUT",body:JSON.stringify({answer,marked_for_review:marked,revision:attempt.revision})});setAttempt({...attempt,revision:x.revision,responses:{...attempt.responses,[qid]:{answer,marked_for_review:marked}}})}}/>}
 {view==="result"&&attempt&&<Result attempt={attempt}/>}</main>
}
function ImportSummary({job,open}:{job:ImportJob;open:()=>void}){const labels:Record<ImportJob["status"],string>={uploaded:"Queued",processing:"Processing",review:"Needs review",failed:"Needs attention",approved:"Review complete"};return <article className="row import-row"><div><b>Question paper import</b><small>{job.meta?.phase||labels[job.status]}{job.meta?.question_count!==undefined?` · ${job.meta.question_count} questions found`:""}</small></div><div><span className={`badge ${job.status}`}>{labels[job.status]}</span><button onClick={open}>{job.status==="review"?"Review":"View progress"}</button></div></article>}
function TeacherHome({tests,questions,jobs,openImport}:{tests:any[];questions:Question[];jobs:ImportJob[];openImport:(id:string)=>void}){const actionable=jobs.filter(job=>job.status!=="approved");return <div className="page"><p className="eyebrow">TEACHER WORKSPACE</p><h1>Assessment control centre</h1><div className="stats"><Card><b>{tests.length}</b><span>Tests</span></Card><Card><b>{questions.length}</b><span>Questions</span></Card><Card><b>{questions.filter(q=>q.approved).length}</b><span>Approved</span></Card><Card><b>{actionable.length}</b><span>Imports to track</span></Card></div>{actionable.length>0&&<Card><h2>Import notifications</h2><p>These imports are saved to your workspace and remain visible after a refresh.</p>{actionable.map(job=><ImportSummary key={job.id} job={job} open={()=>openImport(job.id)}/>)}</Card>}<Card><h2>Your assessments</h2>{tests.map(t=><article className="row" key={t.id}><div><b>{t.title}</b><small>{t.subject} · {t.question_count} questions · {Math.ceil(t.duration_seconds/60)} min</small></div><div><span className={`badge ${t.status}`}>{t.status}</span>{t.status==="draft"&&<button onClick={()=>api(`/tests/${t.id}/publish`,{method:"POST"}).then(()=>location.reload())}>Publish</button>}</div></article>)||<p>No assessments yet.</p>}</Card></div>}
function ImportScreen({onDone,job,jobs,selectJob,refresh,reviewOnly=false}:{onDone:(x:ImportJob)=>void;job:ImportJob|null;jobs:ImportJob[];selectJob:(id:string)=>void;refresh:()=>void;reviewOnly?:boolean}){const [busy,setBusy]=useState(false),[error,setError]=useState("");useEffect(()=>{if(!job&&jobs[0])selectJob(jobs[0].id)},[job,jobs,selectJob]);useEffect(()=>{if(reviewOnly&&job&&!job.questions)refresh()},[reviewOnly,job?.id]);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");try{const f=new FormData(e.currentTarget);const r=await fetch("/api/teacher/imports",{method:"POST",credentials:"include",body:f});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:"Upload failed"}))).detail||"Upload failed");onDone(await r.json());e.currentTarget.reset()}catch(err:any){setError(err.message)}finally{setBusy(false)}};const active=job?.status==="uploaded"||job?.status==="processing";return <div className={`page ${reviewOnly?"review-workspace":"narrow"}`}><p className="eyebrow">{reviewOnly?"PAPER REVIEW":"AI-ASSISTED IMPORT"}</p><h1>{reviewOnly?"Review imported papers":"Import a paper for review"}</h1>{!reviewOnly&&<Card><form onSubmit={submit}><label>Question paper PDF<input required name="question_paper" type="file" accept="application/pdf"/></label><label>Answer key PDF <span className="optional">(optional)</span><input name="answer_key" type="file" accept="application/pdf"/></label><button disabled={busy}>{busy?"Uploading paper…":"Upload and start extraction"}</button></form>{error&&<p className="error">{error}</p>}<p>Each upload is saved as its own paper and appears in the dedicated review workspace.</p></Card>}{reviewOnly&&<div className="review-layout"><aside className="paper-queue"><h2>Paper queue</h2>{jobs.length?jobs.map(item=><button className={item.id===job?.id?"selected":""} key={item.id} onClick={()=>selectJob(item.id)}><b>{item.filename||"Question paper"}</b><span className={`badge ${item.status}`}>{item.status}</span><small>{item.meta?.question_count||0} questions · {item.meta?.phase||"Queued"}</small></button>):<p>No papers uploaded yet.</p>}</aside><div className="review-main">{job&&<ImportReview job={job} active={!!active} refresh={refresh}/>}</div></div>}{!reviewOnly&&null}</div>}
function ImportReview({job,active,refresh}:{job:ImportJob;active:boolean;refresh:()=>void}){const [busy,setBusy]=useState(false);const reextract=async()=>{setBusy(true);try{await api(`/teacher/imports/${job.id}/reextract`,{method:"POST"});await refresh()}finally{setBusy(false)}};return <><Card className="import-status"><div className="status-heading"><div><p className="eyebrow">IMPORT PROGRESS</p><h2>{job.filename||"Question paper"}</h2><p>{job.meta?.phase||"Checking import status"}{job.meta?.question_count!==undefined?` — ${job.meta.question_count} questions extracted.`:""}</p></div><span className={`badge ${job.status}`}>{job.status}</span></div>{active&&<div className="progress"><i/><i/><i/></div>}<div className="review-actions"><a href={`/api/teacher/imports/${job.id}/source`} target="_blank" rel="noreferrer">Open source PDF</a>{!active&&job.status!=="approved"&&<button className="secondary-action" onClick={reextract} disabled={busy}>{busy?"Restarting…":"Re-extract paper"}</button>}<button onClick={refresh}>Refresh</button></div>{job.error&&<p className="error">{job.error}</p>}</Card>{active?<Card><p>The extraction worker is processing this paper. It will update automatically while this view is open.</p></Card>:job.questions?.map((q:Question)=><Card key={q.id} className="review-question"><QuestionCard q={q}/>{!q.approved&&<button onClick={async()=>{await api(`/teacher/imports/${job.id}/questions/${q.id}/approve`,{method:"POST"});refresh()}}>Approve question</button>}</Card>)}</>}
function Builder({questions,onDone}:{questions:Question[];onDone:()=>void}){const [selected,setSelected]=useState<string[]>([]);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api("/tests",{method:"POST",body:JSON.stringify({...f,duration_seconds:Number(f.duration_seconds),max_attempts:Number(f.max_attempts),question_ids:selected,results_policy:{mode:"immediate"}})});onDone()};return <div className="page"><p className="eyebrow">TEST BUILDER</p><h1>Create a governed assessment</h1><form onSubmit={submit} className="builder"><Card><input name="title" placeholder="Test title" required/><input name="subject" placeholder="Subject" required/><input name="duration_seconds" type="number" min="60" defaultValue="3600" required/><input name="max_attempts" type="number" min="1" defaultValue="1" required/><button disabled={!selected.length}>Create draft ({selected.length})</button></Card><Card><h2>Approved question bank</h2>{questions.filter(q=>q.approved).map(q=><label className="selectq" key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={()=>setSelected(x=>x.includes(q.id)?x.filter(id=>id!==q.id):[...x,q.id])}/><QuestionCard q={q}/></label>)}</Card></form></div>}
function StudentHome({tests,start}:{tests:any[];start:(id:string)=>void}){return <div className="page"><p className="eyebrow">STUDENT PORTAL</p><h1>Scheduled assessments</h1><div className="cards">{tests.map(t=><Card key={t.id}><span className="badge published">Available</span><h2>{t.title}</h2><p>{t.subject} · {t.question_count} questions · {Math.ceil(t.duration_seconds/60)} minutes</p><button onClick={()=>start(t.id)}>Start assessment</button></Card>)||<Card>No assessment invitations are currently available.</Card>}</div></div>}
function optionMarkdown(option:any){if(typeof option==="string")return option;if(option&&typeof option==="object")return option.markdown||option.text||option.value||"";return String(option||"")}
function QuestionCard({q}:{q:Question}){return <article className="question"><b>{q.source_number?`Q${q.source_number} · `:""}{q.kind.replaceAll("_"," ")}</b><p><MathText value={q.stem_markdown}/></p>{q.diagrams?.map((d:any,i:number)=><img className="diagram" key={i} src={`/api/media/questions/${q.id}/${i}`} alt={d.alt||"Question diagram"}/>)}{q.options?.map((o:any,i:number)=><div key={i} className="option"><span className="option-letter">{String.fromCharCode(65+i)}</span><MathText value={optionMarkdown(o)}/></div>)}{q.confidence!==undefined&&<small>Extraction confidence: {Math.round(q.confidence*100)}%</small>}</article>}
function Exam({attempt,index,setIndex,update,finish}:{attempt:any;index:number;setIndex:(n:number)=>void;update:(q:string,a:any,m:boolean)=>void;finish:()=>void}){const q=attempt.questions[index],r=attempt.responses[q.id]||{},[now,setNow]=useState(Date.now());useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(x)},[]);const left=Math.max(0,new Date(attempt.ends_at).getTime()-now);useEffect(()=>{if(!left&&!attempt.submitted_at)finish()},[left]);return <div className="exam"><header><b>TestNow Exam Console</b><strong>{Math.floor(left/60000)}:{String(Math.floor(left/1000)%60).padStart(2,"0")}</strong></header><aside>{attempt.questions.map((x:any,i:number)=><button className={`${i===index?"active":""} ${attempt.responses[x.id]?.answer?"answered":""}`} key={x.id} onClick={()=>setIndex(i)}>{i+1}</button>)}</aside><section><p>QUESTION {index+1} OF {attempt.questions.length}</p><QuestionCard q={q}/><div className="answers">{q.options.map((o:any,i:number)=><button key={i} className={JSON.stringify(r.answer)===JSON.stringify({option:i})?"chosen":""} onClick={()=>update(q.id,{option:i},r.marked_for_review)}>{String.fromCharCode(65+i)}</button>)}</div><footer><button onClick={()=>update(q.id,null,r.marked_for_review)}>Clear response</button><button onClick={()=>update(q.id,r.answer,!r.marked_for_review)}>{r.marked_for_review?"Unmark review":"Mark for review"}</button><button onClick={()=>setIndex(Math.min(index+1,attempt.questions.length-1))}>Save & next</button><button className="danger" onClick={finish}>Submit test</button></footer></section></div>}
function Result({attempt}:{attempt:any}){const [data,setData]=useState<any>();useEffect(()=>{api(`/results/${attempt.id}`).then(setData).catch(e=>setData({error:e.message}))},[attempt.id]);if(!data)return <div className="page">Loading result…</div>;if(data.error)return <div className="page"><h1>Result pending</h1><p>{data.error}</p></div>;return <div className="page"><h1>Score: {data.attempt.score}</h1>{data.questions.map((q:Question&{response:any;correct:boolean;points:number})=><Card key={q.id}><QuestionCard q={q}/><p>Your response: {JSON.stringify(q.response)} · {q.correct?"Correct":"Incorrect"} · {q.points} marks</p><p><MathText value={q.solution_markdown||"Solution pending."}/></p></Card>)}</div>}
